import raw from '../data/playerStats.json';

/**
 * One entry per playoff player. Generated by `drl_generate.py` into
 * `src/data/playerStats.json` and imported at build time. This is
 * purely static reference data — no Supabase, no fetch, no runtime
 * recomputation. Re-run the Python script to refresh.
 */
export interface PlayerStats {
  rank: number;
  name: string;
  total: number;
  /** Length 8. null = seed not played. */
  seeds: Array<number | null>;
  country: string | null;
  countryName: string | null;
  avatar: string | null;
  twitch: string | null;
  rage: number | null;
  bait: number | null;
  cons: number | null;
  reach: {
    top16: number;
    top8: number;
    top4: number;
    finalist: number;
    champion: number;
  };
  bracketEntry: 'Winners' | 'Losers';
}

interface PairwiseEntry {
  p1Win: number;
}

interface PlayerStatsFile {
  generatedAt: string | null;
  players: PlayerStats[];
  pairwise?: Record<string, PairwiseEntry>;
}

const file = raw as PlayerStatsFile;

/** All 32 players, sorted by qualifier rank ascending. */
export const PLAYER_STATS: PlayerStats[] = file.players
  .slice()
  .sort((a, b) => a.rank - b.rank);

export const GENERATED_AT: string | null = file.generatedAt;

// ---------------------------------------------------------------------------
// Pairwise win probabilities — used by MatchCard to render win-% badges on
// matches where both slots are filled. Keys in the JSON are sorted-name
// pairs joined with "__" and `p1Win` is the probability that the
// alphabetically-first player wins. Unknown pairs return null.
//
// Lookups are case-insensitive on the React side so that minor casing
// drift between ROSTER displayNames and the Python PLAYOFF_PLAYERS list
// doesn't silently break the feature.

const PAIRWISE_RAW: Record<string, PairwiseEntry> = file.pairwise ?? {};

// Case-insensitive lookup map: lowercase name → canonical cased name as it
// appears in the pairwise keys. We derive it from the player list so we
// know every valid canonical form.
const LOWER_TO_CANON = new Map<string, string>();
for (const p of PLAYER_STATS) {
  LOWER_TO_CANON.set(p.name.toLowerCase(), p.name);
}

function canonicalName(name: string): string | null {
  return LOWER_TO_CANON.get(name.toLowerCase()) ?? null;
}

/**
 * Returns the model's win probabilities for a matchup between two players,
 * or null if the pair is unknown (e.g. one of the names isn't in the
 * roster, or the pairwise table hasn't been populated by the simulator).
 *
 * `aWin + bWin === 1`.
 */
export function getWinProbability(
  playerA: string,
  playerB: string,
): { aWin: number; bWin: number } | null {
  const canonA = canonicalName(playerA);
  const canonB = canonicalName(playerB);
  if (!canonA || !canonB || canonA === canonB) return null;

  const [first, second] = [canonA, canonB].sort();
  const entry = PAIRWISE_RAW[`${first}__${second}`];
  if (!entry) return null;

  // The stored p1Win is "first wins"; flip if caller asked about the other.
  const firstWins = entry.p1Win;
  const aWin = canonA === first ? firstWins : 1 - firstWins;
  return { aWin, bWin: 1 - aWin };
}

/** Find a player by their playoff display name. */
export function playerStatsByName(name: string): PlayerStats | undefined {
  return PLAYER_STATS.find((p) => p.name === name);
}

// ---------------------------------------------------------------------------
// Sort options for the Players tab dropdown

export type PlayerSortKey =
  | 'rank'
  | 'champion'
  | 'finalist'
  | 'top4'
  | 'top8'
  | 'top16'
  | 'rage'
  | 'bait'
  | 'cons'
  | 'total';

export const SORT_OPTIONS: ReadonlyArray<{ key: PlayerSortKey; label: string }> = [
  { key: 'rank',     label: 'Qualifier Rank' },
  { key: 'champion', label: 'Champion %' },
  { key: 'finalist', label: 'Finalist %' },
  { key: 'top4',     label: 'Top 4 %' },
  { key: 'top8',     label: 'Top 8 %' },
  { key: 'top16',    label: 'Top 16 %' },
  { key: 'rage',     label: 'RAGE Factor' },
  { key: 'bait',     label: 'BAIT Chance' },
  { key: 'cons',     label: 'Consistency' },
  { key: 'total',    label: 'Total Score' },
];

/** Returns a new array sorted by the given key. */
export function sortPlayers(
  players: PlayerStats[],
  key: PlayerSortKey,
): PlayerStats[] {
  const sorted = players.slice();
  switch (key) {
    case 'rank':
      sorted.sort((a, b) => a.rank - b.rank);
      break;
    case 'total':
      sorted.sort((a, b) => b.total - a.total || a.rank - b.rank);
      break;
    case 'rage':
      sorted.sort((a, b) => (b.rage ?? 0) - (a.rage ?? 0) || a.rank - b.rank);
      break;
    case 'bait':
      // Lower bait = more reliable; sort ascending so "safest bet" is on top.
      sorted.sort((a, b) => (a.bait ?? 99) - (b.bait ?? 99) || a.rank - b.rank);
      break;
    case 'cons':
      sorted.sort((a, b) => (b.cons ?? 0) - (a.cons ?? 0) || a.rank - b.rank);
      break;
    case 'champion':
    case 'finalist':
    case 'top4':
    case 'top8':
    case 'top16':
      sorted.sort(
        (a, b) => b.reach[key] - a.reach[key] || a.rank - b.rank,
      );
      break;
  }
  return sorted;
}

/** Utility used by PlayerCard for the "Best seed" row. */
export function bestSeed(
  seeds: Array<number | null>,
): { score: number; index: number } | null {
  let best = -1;
  let idx = -1;
  seeds.forEach((s, i) => {
    if (s !== null && s > best) {
      best = s;
      idx = i;
    }
  });
  return best > 0 ? { score: best, index: idx } : null;
}
